BACK-1117: Bitcoin API Swagger
LedgerHQ/lama pull request #106
Opened 2020-11-23 10:59 UTC by jjayet-ledger

## What is this about?

What is says on the title, we now have a Swagger

## Cute picture of lama
![lama](https://res.cloudinary.com/teepublic/image/private/s--_aecr6rM--/c_fit,g_north_west,h_645,w_840/co_000000,e_outline:40/co_000000,e_outline:inner_fill:1/co_ffffff,e_outline:40/co_ffffff,e_outline:inner_fill:1/co_bbbbbb,e_outline:3:1000/c_mpad,g_center,h_1260,w_1260/b_rgb:eeeeee/c_limit,f_jpg,h_630,q_90,w_630/v1576074880/production/designs/7149423_0.jpg)

2020-11-23 15:32 UTC, nukky94 requested changes

2020-11-23 15:32 UTC, nukky94 commented on coins/bitcoin/api/doc/lama-btc-api.yaml
> +  - url: https://TBD/
you could setup a default value with the `http://localhost:8080`

2020-11-23 15:32 UTC, nukky94 commented on coins/bitcoin/api/doc/lama-btc-api.yaml
> +      summary: Create a user account and trigger synchronization
Register an account in order to trigger synchronization

2020-11-23 15:32 UTC, nukky94 commented on coins/bitcoin/api/doc/lama-btc-api.yaml
> +    CreationRequest:
RegisterAccountRequest

2020-11-23 15:32 UTC, nukky94 commented on coins/bitcoin/api/doc/lama-btc-api.yaml
> +          description: The created user account
Registered account

2020-11-23 15:32 UTC, nukky94 commented on coins/bitcoin/api/doc/lama-btc-api.yaml
> +    AccountCreated:
RegisterAccountResponse

2020-11-23 15:32 UTC, nukky94 commented on coins/bitcoin/api/doc/lama-btc-api.yaml
> +      summary: Get a user account by id
Don't necessary to precise `user account`, just `account` is enough.
(Same for all occurences below)

2020-11-23 15:32 UTC, nukky94 commented on coins/bitcoin/api/doc/lama-btc-api.yaml
> +    UpdateRequest:
UpdateAccountRequest

2020-11-23 15:32 UTC, nukky94 commented on coins/bitcoin/api/doc/lama-btc-api.yaml
> +            maximum: 20
Let's cap it to 1000 for maximum value (we need to apply it in the code)

2020-11-23 15:32 UTC, nukky94 commented on coins/bitcoin/api/doc/lama-btc-api.yaml
> +      summary: Get operations from an account
Get account operations

2020-11-23 15:32 UTC, nukky94 commented on coins/bitcoin/api/doc/lama-btc-api.yaml
> +            format: timestamp
```
type: string
format: instant
```

2020-11-23 15:32 UTC, nukky94 commented on coins/bitcoin/api/doc/lama-btc-api.yaml
> +    AccountResponse:
GetAccountResponse

2020-11-23 15:32 UTC, nukky94 commented on coins/bitcoin/api/doc/lama-btc-api.yaml
> +          description: 'How often do we look for new operations'
Could you precise the unit (in seconds) ?

2020-11-23 15:32 UTC, nukky94 commented on coins/bitcoin/api/doc/lama-btc-api.yaml
> +          type: string
`format: big integer`
same for all big integer converted to string for json convenience

2020-11-23 15:32 UTC, nukky94 commented on coins/bitcoin/api/doc/lama-btc-api.yaml
> +          example: 'MainNet'
`enum: [MainNet, TestNet, RegTest]`

2020-11-23 15:32 UTC, nukky94 commented on coins/bitcoin/api/doc/lama-btc-api.yaml
> +          type: integer
```
type: string
enum: [bitcoin]
```

2020-11-23 15:32 UTC, nukky94 commented on coins/bitcoin/api/doc/lama-btc-api.yaml
> +          example: 'btc'
`enum: [btc, btc_testnet, btc_regtest]`

2020-11-23 15:42 UTC, jjayet-ledger commented on coins/bitcoin/api/doc/lama-btc-api.yaml
> +  description: Returns beautifull curated photos
Ahahah oops

2020-11-23 15:42 UTC, jjayet-ledger commented on coins/bitcoin/api/doc/lama-btc-api.yaml
> +  - url: https://TBD/
Oh yeah thx

2020-11-23 18:11 UTC, nukky94 approved these changes

2020-11-24 09:09 UTC, nukky94 requested changes
Oh, I didn't see you didn't finish

2020-11-24 13:54 UTC, nukky94 approved these changes

2020-11-24 14:03 UTC, merged