Back 1169 Testnet handled by Lama
LedgerHQ/lama pull request #121
Opened 2020-11-30 14:52 UTC by mbasire-ledger

## What is this about?

Testnet has to be handled by Lama. It will be the first fork to be handled.

## Cute picture of lama
![lama](https://user-images.githubusercontent.com/11653587/90911060-b5c13280-e3d8-11ea-9e92-d55e347836e2.jpg)

2020-11-30 16:48 UTC, nukky94 requested changes

2020-11-30 16:48 UTC, nukky94 commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Interpreter.scala
> +                coin = Coin.fromKey(request.coinId).get,
better to validate and parse correctly the request

2020-11-30 17:43 UTC, mbasire-ledger commented on account-manager/src/main/resources/db/migration/V2__coin_type.sql
> +ALTER TYPE coin ADD VALUE 'btc_testnet' ;
ok

2020-11-30 17:44 UTC, mbasire-ledger commented on coins/bitcoin/api/src/it/resources/application.conf
> +    coins {
ok

2020-11-30 17:44 UTC, mbasire-ledger commented on coins/bitcoin/api/src/it/scala/co/ledger/lama/bitcoin/api/AccountControllerIT.scala
> +  def waitBalancedUpdated(
ok

2020-11-30 17:44 UTC, mbasire-ledger commented on coins/bitcoin/api/src/it/scala/co/ledger/lama/bitcoin/api/AccountControllerIT.scala
> +            balancedNotification <- AccountNotifications.waitBalancedUpdated(notifications)
ok

2020-11-30 17:44 UTC, mbasire-ledger commented on coins/bitcoin/api/src/it/scala/co/ledger/lama/bitcoin/api/AccountControllerIT.scala
> +            it should "emit a balanced notification" in {
ok

2020-11-30 17:44 UTC, mbasire-ledger commented on coins/bitcoin/api/src/it/scala/co/ledger/lama/bitcoin/api/AccountControllerIT.scala
> +              balancedNotification.accountId shouldBe accountRegistered.accountId
ok

2020-11-30 17:44 UTC, mbasire-ledger commented on coins/bitcoin/api/src/it/scala/co/ledger/lama/bitcoin/api/ConfigSpec.scala
> +                         )
ok

2020-11-30 17:44 UTC, mbasire-ledger commented on coins/bitcoin/api/src/main/scala/co/ledger/lama/bitcoin/api/utils/ProtobufUtils.scala
> +  // do we need to handle Unrecognized ?
ok

2020-12-01 08:12 UTC, mbasire-ledger commented
Lama bitcoin api is able to handle register request for testnet. The testnet  account will be synchronized.

2020-12-01 08:36 UTC, nukky94 approved these changes
Good work! LGTM

2020-12-01 08:44 UTC, nukky94 commented
TODO:
- Add your gpg key on Github > Settings > SSH and GPG keys
- Merge master and [Sign your commit](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/signing-commits)

2020-12-01 11:20 UTC, closed without merging