Bitcoin interpreter RPC service implementation
LedgerHQ/lama pull request #17
Opened 2020-09-23 08:03 UTC by jjayet-ledger

## What is this about?

Description...

## Cute picture of lama
![44337b67caa020912aaf83c6dc5fb2f0](https://user-images.githubusercontent.com/11653587/90911060-b5c13280-e3d8-11ea-9e92-d55e347836e2.jpg)

2020-09-23 15:38 UTC, nukky94 requested changes

2020-09-23 15:38 UTC, nukky94 commented on coins/bitcoin/interpreter/src/it/scala/co/ledger/lama/bitcoin/interpreter/InterpreterIT.scala
> +            null
🚫 , you can construct an empty `new Metadata()`

2020-09-23 15:38 UTC, nukky94 commented on coins/bitcoin/interpreter/src/it/scala/co/ledger/lama/bitcoin/interpreter/InterpreterIT.scala
> +            null
🚫

2020-09-23 15:38 UTC, nukky94 commented on coins/bitcoin/interpreter/src/it/scala/co/ledger/lama/bitcoin/interpreter/InterpreterIT.scala
> +        null
🚫

2020-09-23 15:38 UTC, nukky94 commented on coins/bitcoin/interpreter/src/it/scala/co/ledger/lama/bitcoin/interpreter/InterpreterIT.scala
> +            new GetTransactionsRequest(accountId = saveTransactionRequest.accountId),
You provide only one field (the first), so it seems not so relevant to explicitly declare the `accountId` field param.
`new GetTransactionsRequest(saveTransactionRequest.accountId)`

2020-09-23 15:38 UTC, nukky94 commented on coins/bitcoin/interpreter/src/it/scala/co/ledger/lama/bitcoin/interpreter/InterpreterIT.scala
> +  "The interpreter" should "save transactions and fetch those transactions" in {
Prefer to use our sugar syntax `IOAssertion` from `co.ledger.lama.common.utils.IOAssertion`

```
"It" should "do something" in IOAssertion in {
 ... // returns an IO[Assert]
}
```

2020-09-23 15:38 UTC, nukky94 commented on coins/bitcoin/interpreter/src/it/scala/co/ledger/lama/bitcoin/interpreter/InterpreterIT.scala
> +      _ = transactions.length shouldBe 3
It's better to have all assertions into the `yield` part

2020-09-23 15:38 UTC, nukky94 commented on coins/bitcoin/interpreter/src/main/protobuf/service.proto
>    ASC = 0;
`DESC = 0` seems better for the default value

2020-09-23 15:38 UTC, nukky94 commented on coins/bitcoin/interpreter/src/main/protobuf/service.proto
>  message GetTransactionsResult {
Hmm, maybe we also need a `truncated` boolean flag to know for the client if there's more results

2020-09-23 15:38 UTC, nukky94 commented on coins/bitcoin/interpreter/src/main/resources/application.conf
> +  url = ${?JDBC_URL}
It shouldn't be the same database (`lama` is for the account-manager).
Also, don't focus on this part, @estrauser-ledger is already working on it in his PR.

2020-09-23 15:38 UTC, nukky94 commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/App.scala
> +      ce <- ExecutionContexts.fixedThreadPool[IO](conf.postgres.poolSize)
Maybe it's the time to refactor this part into the common lama project ^^
`ResourceUtils.postgresTransactor(conf: PostgresConfig)`

2020-09-23 15:38 UTC, nukky94 commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/GrpcServer.scala
> +  def defaultServer(
Same here: `ResourceUtils.grpcServer(conf: GrpcServerConfig, services: List[ServerServiceDefinition)`

2020-09-23 16:04 UTC, vbergeron-ledger commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Config.scala
> +}
I think this should be in commons

2020-09-23 16:04 UTC, vbergeron-ledger commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Config.scala
> +case class GrpcServerConfig(port: Int)
This too no ?

2020-09-23 16:04 UTC, vbergeron-ledger commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/GrpcServer.scala
> +      }
```suggestion
      .foldLeft(ServerBuilder.forPort(conf.port))(_.addService _)
```

2020-09-23 16:04 UTC, vbergeron-ledger commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/GrpcServer.scala
> +      }
I don't think the function in foldLeft is tupled.

2020-09-24 08:22 UTC, jjayet-ledger commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Config.scala
> +case class GrpcServerConfig(port: Int)
Yep, we discussed it with @nukky94 and decided to wait but I agree and I'll do it now.

2020-09-24 11:15 UTC, estrauser-ledger commented
LGTM
I already forgot where the "approve" button was

2020-09-24 12:04 UTC, nukky94 approved these changes

2020-09-24 12:06 UTC, nukky94 requested changes
Sorry, one missing remark

2020-09-24 12:06 UTC, nukky94 commented on coins/bitcoin/interpreter/src/main/protobuf/service.proto
> +  bool truncated = 6;
`truncated` field should be on the response.

2020-09-24 12:18 UTC, jjayet-ledger commented
> Sorry, one missing remark

Done :)

2020-09-24 13:12 UTC, nukky94 commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Interpreter.scala
> +    IO(transactions.getOrElse(bytesToUUID(request.accountId), Nil)).map(GetTransactionsResult(_))
Missing sorting, filtering and pagination features + tests

2020-09-24 13:49 UTC, jjayet-ledger commented on coins/bitcoin/interpreter/src/it/scala/co/ledger/lama/bitcoin/interpreter/InterpreterIT.scala
> +    val interpreter: Interpreter = new FakeInterpreter()
I just want to avoid side effects and I guess it's not that costly

2020-09-24 13:54 UTC, nukky94 commented on coins/bitcoin/interpreter/src/it/scala/co/ledger/lama/bitcoin/interpreter/InterpreterIT.scala
> +class InterpreterIT extends AnyFlatSpecLike with Matchers {
Actually, it's more an unit test :D
- move to `test/scala`
- rename it to `InterpreterSpec`

2020-09-24 13:57 UTC, nukky94 commented on coins/bitcoin/interpreter/src/it/scala/co/ledger/lama/bitcoin/interpreter/InterpreterIT.scala
> +      transactions.length shouldBe 3
There's a more appropriate matcher in scalatest for size:
`transaction should have size 3`

2020-09-24 13:58 UTC, nukky94 commented on coins/bitcoin/interpreter/src/it/scala/co/ledger/lama/bitcoin/interpreter/InterpreterIT.scala
> +      transactions.head.hash shouldBe "4c93a655-437a-495b-9c51-926ad90852ba",
More safer:
```
transactions.slice(0, 3).map(_.hash) shouldBe List("4c93a655-437a-495b-9c51-926ad90852ba", "7cb3aacc-2aea-4152-8b53-3431f4daece5", "958f7014-4cb7-400a-92cf-1a8540a186bc")

2020-09-24 14:02 UTC, nukky94 commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Interpreter.scala
> +    def getDefaultValues =
val limit

2020-09-24 14:03 UTC, nukky94 commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Interpreter.scala
> +    def filterTransactions(request: GetTransactionsRequest) = {
Actually, we don't really need inner function

2020-09-24 14:19 UTC, nukky94 commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Interpreter.scala
> +          .exists(_.length != filteredTransactions.length)
Actually, the meaning of `truncated`is if there's more transaction on the next range (maybe `hasNext` or `hasMore` are more appropriate names):

allTxs = 10 elts
For `offset = 0`, `limit = 5` => true
For `offset = 0`, `limit = 5` => false

You could easily have this assertion:
```
val filteredTxs = transactions
        .getOrElse(bytesToUUID(request.accountId), Seq())
        .filter(_.block.exists { _.height >= request.blockHeight })
        .sortWith((t, t2) => {
          request.sort match {
            case SortingOrder.DESC => t.hash > t2.hash
            case _                 => t.hash < t2.hash
          }
        })

val paginatedTxs = sortedTxs.slice(request.offset, request.offset + request.limit)
val hasMore = filteredTxs.splitAt(request.offset + request.limit)._2.nonEmpty
```

2020-09-24 14:32 UTC, jjayet-ledger commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Interpreter.scala
> +          .exists(_.length != filteredTransactions.length)
Oh, ok thx a lot, I didn't get that

2020-09-24 14:59 UTC, nukky94 commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Interpreter.scala
> +    }
No needed to `map`, just construct directly `GetTransactionsResult(slicedTxs, hasMore)`

2020-09-24 14:59 UTC, nukky94 approved these changes
Last cosmetic remark and LGTM :)

2020-09-24 15:00 UTC, jjayet-ledger commented
> Last cosmetic remark and LGTM :)

Thx :)

2020-09-24 15:47 UTC, merged