WIP: BACK-1335, BACK-1336 & BACK-1329  mempool balance & operations
LedgerHQ/lama pull request #178
Opened 2021-01-15 11:00 UTC by estrauser-ledger

## What is this about?

Mempool (Unconfirmed) Transactions are added to :
- current balance as a new field
- balance history as a new point in the timeline at time "now"
- operations list as a new endpoint

## Cute picture of lama
![llama](https://user-images.githubusercontent.com/1628443/104717186-39cddb00-5729-11eb-8035-782fac36aa8c.jpg)

2021-01-27 12:09 UTC, nukky94 requested changes

2021-01-27 12:09 UTC, nukky94 commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/services/TransactionQueries.scala
> +          FROM unconfirmed_transaction_tmp
to rename to reflect the idea to have a table as a cache

2021-01-27 12:09 UTC, nukky94 commented on coins/bitcoin/protobuf/src/main/protobuf/interpreter.proto
> +  rpc GetUnconfirmedUTXOs(GetUTXOsRequest) returns (GetUnconfirmedUTXOsResult) {}
to remove (to do in another PR)

2021-01-27 12:09 UTC, nukky94 commented on coins/bitcoin/protobuf/src/main/protobuf/operation.proto
> +  string unconfirmedBalance = 5;
snake_case

2021-01-27 14:58 UTC, estrauser-ledger commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Interpreter.scala
> +      _ <- transactionService.deleteUnconfirmedTransaction(accountId)
https://ledgerhq.atlassian.net/browse/BACK-1461

2021-01-27 16:56 UTC, estrauser-ledger commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/services/BalanceService.scala
> +          val mempoolBalance = txs.foldLeft(BigInt(0)) { (balance, tx) =>
There's no getUnconfirmedOperations (yet), so maybe later but i'll keep it like this for now

2021-01-28 14:41 UTC, estrauser-ledger commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/services/OperationService.scala
> +  def toUnconfirmedOperation(accountId: UUID, tx: TransactionView): List[OperationToSave] =
moved to : OperationToSave.fromTransactionView()
because TransactionView is a model shared by all components but OperationToSave is only used in Interpreter

2021-01-29 09:50 UTC, nukky94 approved these changes

2021-01-29 10:00 UTC, estrauser-ledger commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/services/OperationService.scala
> +  def removeFromCursor(accountId: UUID, blockHeight: Long): IO[Int] =
https://ledgerhq.atlassian.net/browse/BACK-1467

2021-01-29 10:02 UTC, estrauser-ledger commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/models/implicits.scala
> +            block =
https://ledgerhq.atlassian.net/browse/BACK-1468

2021-01-29 10:02 UTC, estrauser-ledger commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/models/implicits.scala
>    implicit lazy val readOperation: Read[Operation] =
also in https://ledgerhq.atlassian.net/browse/BACK-1461

2021-01-29 10:10 UTC, merged