Back 1332 fetch pending transactions
LedgerHQ/lama pull request #185
Opened 2021-01-27 09:31 UTC by mbasire-ledger

## What is this about?

      * syncMempool step added to the synchronizeAccount job
      * InterpreterClient.saveUnconfirmedTransaction is stubbed
      * Eventual duplicated addresses before calling interpreter.compute
      * Mempool transactions step extracted in the TransactionsCrawler

## Cute picture of lama
![lama](https://media.giphy.com/media/l3vRfG7oxKdJGnpFC/giphy.gif)

2021-01-27 15:03 UTC, nukky94 requested changes

2021-01-27 15:03 UTC, nukky94 commented on coins/bitcoin/worker/src/test/scala/co/ledger/lama/bitcoin/worker/TransactionsCrawlerTest.scala
> +  it should "mark all met addresses as marked in the keychain" in {
typo

2021-01-27 15:03 UTC, nukky94 commented on coins/bitcoin/worker/src/test/scala/co/ledger/lama/bitcoin/worker/TransactionsCrawlerTest.scala
> +  it should "send transactions and corresponding used addresses to the interpreter" in {}
nice test

2021-01-27 15:03 UTC, nukky94 commented on coins/bitcoin/worker/src/test/scala/co/ledger/lama/bitcoin/worker/TransactionsCrawlerTest.scala
> +object Keychain {
`KeychainFixture`

2021-01-27 15:22 UTC, mbasire-ledger commented on coins/bitcoin/worker/src/main/scala/co/ledger/lama/bitcoin/worker/models/BatchResult.scala
> +case class BatchResult[TX <: Transaction](
- [ ]

2021-01-27 19:21 UTC, mbasire-ledger commented on coins/bitcoin/worker/src/test/scala/co/ledger/lama/bitcoin/worker/TransactionsCrawlerTest.scala
> +  it should "mark all met addresses as marked in the keychain" in {
ok

2021-01-28 08:14 UTC, mbasire-ledger commented on coins/bitcoin/common/src/main/scala/co/ledger/lama/bitcoin/common/clients/http/ExplorerClient.scala
> +    IOUtils.retry(
A talk with explorer team let us suppose we can hit the explorer with no specific strategy. 
The `http 500 bug` (which may be fixed soon) may happen randomly and can not be fixed we a better strategy than recalling as soon as a 500 is returned.  The explorer can support `easily` 20 successive call.

2021-01-28 09:56 UTC, nukky94 approved these changes

2021-01-28 10:26 UTC, merged