BACK-m1445 Mempool Utxos
LedgerHQ/lama pull request #188
Opened 2021-01-29 18:03 UTC by estrauser-ledger

## What is this about?

- Get Unconfirmed UTXOs gRPC Interpreter endpoint
- Flag Utxos used in Mempool

## Cute picture of lama
![04bf0a8f3a9383b7e06ad0043431782d](https://user-images.githubusercontent.com/1628443/106310970-b2be4e00-6264-11eb-94c4-b1d6939d4875.jpg)

2021-01-29 18:09 UTC, estrauser-ledger commented
Cute Llama is a Meme... Pool

2021-02-02 14:11 UTC, nukky94 requested changes

2021-02-02 14:11 UTC, nukky94 commented on coins/bitcoin/common/src/main/scala/co/ledger/lama/bitcoin/common/clients/grpc/InterpreterClient.scala
> +  def getUnconfirmedUTXOs(
`getUnconfirmedUtxos` (no uppercase)

2021-02-02 14:11 UTC, nukky94 commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/services/OperationService.scala
> +              output.derivation.get,
not safe !

2021-02-02 15:08 UTC, nukky94 approved these changes

2021-02-02 15:09 UTC, merged