WIP: BACK-900 Select transactions from db
LedgerHQ/lama pull request #19
Opened 2020-09-25 14:05 UTC by estrauser-ledger

## What is this about?

- doobie request
- IT test PG

## Cute picture of lama
![images](https://user-images.githubusercontent.com/1628443/94276669-d4bb6300-ff48-11ea-95a3-19ec6021ca76.jpeg)

2020-09-28 08:55 UTC, onyb commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Queries.scala
> +          WHERE hash = $hash::bytea
Why a byte array and not a string?

2020-09-28 09:16 UTC, jjayet-ledger requested changes

2020-09-28 09:16 UTC, jjayet-ledger commented on coins/bitcoin/interpreter/src/it/scala/co.ledger.lama.bitcoin.interpreter/TestResources.scala
> +    )
You should replace that with:
`db <- postgresTransactor(conf.postgres)`

2020-09-28 10:09 UTC, estrauser-ledger commented on coins/bitcoin/interpreter/src/it/scala/co.ledger.lama.bitcoin.interpreter/TestResources.scala
> +    )
Oh yes :+1:

2020-09-28 16:23 UTC, estrauser-ledger commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Queries.scala
> +          WHERE hash = $hash::bytea
It was Valentin's suggestion, it takes less space : https://github.com/LedgerHQ/lama/pull/15 (somewhere in Valentin's change suggestions)

2020-09-29 11:43 UTC, nukky94 requested changes

2020-09-29 11:43 UTC, nukky94 commented on build.sbt
> +    flywayPassword := "serge_btc"
For convenience, no need to have an other user, you can use the only and unique `serge lama`

2020-09-29 11:43 UTC, nukky94 commented on coins/bitcoin/interpreter/src/it/resources/application.conf
> +  password = "serge_btc"
lama serge

2020-09-29 11:43 UTC, nukky94 commented on coins/bitcoin/interpreter/src/it/resources/application.conf
> +  url = "jdbc:postgresql://localhost:5433/lama_btc"
It's better to have a dedicated db`test_lama_btc` for IT tests

2020-09-29 11:43 UTC, nukky94 commented on coins/bitcoin/interpreter/src/it/resources/db/migration/V999__populate_transactions.sql
> +INSERT INTO block VALUES (
why v999 ?

2020-09-29 11:43 UTC, nukky94 commented on coins/bitcoin/interpreter/src/it/scala/co.ledger.lama.bitcoin.interpreter/QueriesIT.scala
> +            transaction.map(_.accountId should be(transactionTest.accountId))
`transaction.map(_.accountId) should contain only transactionTest.accountId`

2020-09-29 11:43 UTC, nukky94 commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Queries.scala
> +  def fetchTransactionForAccount(
`fetchTransactions`

2020-09-29 11:43 UTC, nukky94 commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Queries.scala
> +  def fetchTransaction(hash: String): Stream[ConnectionIO, Transaction] =
`ConnectionIO[Option[Transaction]]`

2020-09-29 11:43 UTC, nukky94 commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Queries.scala
> +      .stream
.option

2020-09-29 11:43 UTC, nukky94 commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Queries.scala
> +  def saveTransaction(tx: Transaction): ConnectionIO[Int] =
To optimize later regarding batch updates:
https://tpolecat.github.io/doobie/docs/07-Updating.html#batch-updates

2020-09-29 11:49 UTC, estrauser-ledger commented on coins/bitcoin/interpreter/src/it/resources/db/migration/V999__populate_transactions.sql
> +INSERT INTO block VALUES (
It's a test migration but the names conflict with the main migrations and there's already a V1. I could name it V2 , but when there'll be a V2 in the main migrations, we'll have to rename the test migration to be V3, and so on.
So I went with 999 (wich is OVERKILL!) but we could name it whatever, what's your suggestion ?

2020-09-29 11:54 UTC, estrauser-ledger commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Queries.scala
> +  def fetchTransactionForAccount(
I'll also remove the fetchTransaction which does not have the accountId parameter, it doesn't make any sense.

2020-09-29 12:25 UTC, nukky94 commented on coins/bitcoin/interpreter/src/it/resources/db/migration/V999__populate_transactions.sql
> +INSERT INTO block VALUES (
Hmm, maybe it's the wrong way to use migration in order to insert data for testing :D

2020-09-29 12:40 UTC, nukky94 approved these changes

2020-09-29 12:41 UTC, merged