BACK-1545 Use EffectiveValue
LedgerHQ/lama pull request #207
Opened 2021-02-17 15:05 UTC by estrauser-ledger

## What is this about?

Compute fees into coin selection

## Cute picture of lama
![bouf](https://user-images.githubusercontent.com/1628443/108223309-f73d5b00-7139-11eb-8b26-4106fa6d958c.gif)

2021-02-19 15:19 UTC, mbasire-ledger requested changes

2021-02-19 15:19 UTC, mbasire-ledger commented on coins/bitcoin/transactor/src/main/scala/co/ledger/lama/bitcoin/transactor/services/CoinSelectionService.scala
>        case head :: tail =>
`utxo` instead of `head` maybe ?

2021-02-22 14:03 UTC, nukky94 approved these changes

2021-02-22 15:02 UTC, mbasire-ledger approved these changes

2021-02-22 15:02 UTC, merged