Back 1524 address validation endpoint
LedgerHQ/lama pull request #217
Opened 2021-02-23 14:01 UTC by mbasire-ledger

## What is this about?

Description...

## Cute picture of lama
![lama](https://user-images.githubusercontent.com/11653587/90911060-b5c13280-e3d8-11ea-9e92-d55e347836e2.jpg)

2021-02-24 15:16 UTC, estrauser-ledger commented on coins/bitcoin/transactor/src/main/scala/co/ledger/lama/bitcoin/transactor/TransactorGrpcService.scala
> +}
prefix with protobuf to isolate generated case classes

2021-02-24 15:16 UTC, estrauser-ledger commented on coins/bitcoin/transactor/src/main/scala/co/ledger/lama/bitcoin/transactor/TransactorGrpcService.scala
> +}
same

2021-02-24 15:16 UTC, estrauser-ledger commented on coins/bitcoin/transactor/src/main/scala/co/ledger/lama/bitcoin/transactor/TransactorGrpcService.scala
> +      transactor.bitcoinLibClient
I'd rather have this done directly in the Transactor. I know it needs useless case classes, we should discuss about this.

2021-02-24 15:16 UTC, estrauser-ledger commented on coins/bitcoin/transactor/src/main/scala/co/ledger/lama/bitcoin/transactor/clients/grpc/BitcoinLibClient.scala
> +  case class Address(value: String)               extends AnyVal
I'd put this in bitcoin.common.models

2021-02-24 15:16 UTC, estrauser-ledger commented on coins/bitcoin/transactor/src/main/scala/co/ledger/lama/bitcoin/transactor/clients/grpc/BitcoinLibClient.scala
> +      case BitcoinNetwork.Unspecified => libgrpc.BitcoinNetwork.BITCOIN_NETWORK_UNSPECIFIED
network.toLibGrpxProto 
it's an implicit method declared in transactor.models.implicits

2021-02-24 15:16 UTC, estrauser-ledger commented on coins/bitcoin/transactor/src/main/scala/co/ledger/lama/bitcoin/transactor/clients/grpc/BitcoinLibClient.scala
> +  }
I'd rather have a 'fromProto' in the dedicated case classes (I know it's not fun)

2021-02-25 09:05 UTC, mbasire-ledger commented on coins/bitcoin/transactor/src/main/scala/co/ledger/lama/bitcoin/transactor/clients/grpc/BitcoinLibClient.scala
> +  case class Address(value: String)               extends AnyVal
Thoses 2 case classes are part of the contract exposed by the BitcoinLibClient. Only the client of BitcoinLibClient needs it. Why should be move them to a common package ?

2021-02-25 10:24 UTC, vbergeron-ledger commented on coins/bitcoin/api/src/main/scala/co/ledger/lama/bitcoin/api/routes/AccountController.scala
> +
Maybe seed Validated :
https://typelevel.org/cats/datatypes/validated.html

2021-02-26 08:21 UTC, mbasire-ledger commented on coins/bitcoin/transactor/src/main/scala/co/ledger/lama/bitcoin/transactor/clients/grpc/BitcoinLibClient.scala
> +      case BitcoinNetwork.Unspecified => libgrpc.BitcoinNetwork.BITCOIN_NETWORK_UNSPECIFIED
ok

2021-03-03 11:00 UTC, estrauser-ledger approved these changes

2021-03-03 14:07 UTC, RomanWlm requested changes

2021-03-03 14:07 UTC, RomanWlm commented on coins/bitcoin/transactor/src/main/scala/co/ledger/lama/bitcoin/transactor/Transactor.scala
> +            _ <- log.info(s"GetSmartFees feeLevel: $feeLevel - feeSatPerKb: $smartFee ")
Log account UID to better tracking

2021-03-03 16:58 UTC, mbasire-ledger commented on coins/bitcoin/api/src/main/scala/co/ledger/lama/bitcoin/api/routes/AccountController.scala
> +
We need to fold all the valid addresses AND the invalid adresses. Validated seems to not fit well in that case.

2021-03-03 20:56 UTC, mbasire-ledger commented on coins/bitcoin/transactor/src/main/scala/co/ledger/lama/bitcoin/transactor/Transactor.scala
> +            _ <- log.info(s"GetSmartFees feeLevel: $feeLevel - feeSatPerKb: $smartFee ")
Added. But there is many other log message without an account id. I will not add account id on all messages logged in that  PR. It deserves its own PR.

2021-03-04 10:28 UTC, merged