BACK 824 - Integrate bitcoin keychain service
LedgerHQ/lama pull request #22
Opened 2020-09-30 12:48 UTC by nukky94

## What is this about?

- Integrate keychain service to get used addresses and fetch transactions
- Move shared codes to btcCommon

## Cute picture of lama
![44337b67caa020912aaf83c6dc5fb2f0](https://img.huffingtonpost.com/asset/5c92f545240000f7054df81a.jpeg?ops=scalefit_720_noupscale&format=webp)

2020-09-30 12:49 UTC, nukky94 commented on coins/bitcoin/worker/src/main/scala/co/ledger/lama/bitcoin/worker/Worker.scala
> +  /**
The most important part is here:

2020-09-30 13:01 UTC, nukky94 commented on coins/bitcoin/worker/src/main/scala/co/ledger/lama/bitcoin/worker/Worker.scala
> +  /**
The most important part starts here:

2020-09-30 13:21 UTC, onyb commented on coins/bitcoin/worker/src/main/scala/co/ledger/lama/bitcoin/worker/services/KeychainService.scala
> +          change = Change.CHANGE_UNSPECIFIED, // to both list internal and external
You can just leave it blank if you want.

2020-09-30 13:27 UTC, onyb commented on coins/bitcoin/worker/src/main/scala/co/ledger/lama/bitcoin/worker/Worker.scala
> +              keychainService.markAddressesAsUsed(keychainId, addresses)
Is this correct? Some of the members in `addresses` may not have any associated transactions. You need to perform a set intersection between `addresses` and the input/output addresses in `transactions`.

2020-09-30 13:30 UTC, nukky94 commented on coins/bitcoin/worker/src/main/scala/co/ledger/lama/bitcoin/worker/Worker.scala
> +              keychainService.markAddressesAsUsed(keychainId, addresses)
Hmm, the goal is to mark a batch of addresses (indexes 20 to 40 for example) as used if there's at last one transaction for this batch of addresses.

2020-09-30 14:05 UTC, estrauser-ledger commented
LGTM

2020-10-01 08:13 UTC, jjayet-ledger approved these changes

2020-10-01 08:57 UTC, onyb approved these changes

2020-10-01 09:22 UTC, RomanWlm requested changes

2020-10-01 09:22 UTC, RomanWlm commented on coins/bitcoin/worker/src/it/resources/application.conf
> +  lookahead-size = 20
Is this a client side property ??? 
This is setup at key registration time, right ?

2020-10-01 09:22 UTC, RomanWlm commented on coins/bitcoin/worker/src/it/scala/co/ledger/lama/bitcoin/worker/WorkerIT.scala
> +            val keychainService = new KeychainServiceMock
We will integrate the real keychain on nexts steps ?
You can drop a Jira ticket to keep this in mind

2020-10-01 09:22 UTC, RomanWlm commented on coins/bitcoin/worker/src/it/scala/co/ledger/lama/bitcoin/worker/WorkerIT.scala
> +              conf.keychain.lookaheadSize
🤔

2020-10-01 09:22 UTC, RomanWlm commented on coins/bitcoin/worker/src/it/scala/co/ledger/lama/bitcoin/worker/WorkerIT.scala
> +            val account = AccountIdentifier(keychainId.toString, CoinFamily.Bitcoin, Coin.Btc)
Do we plan tp keep keychain as string on AccountIdentifier model ?

2020-10-01 09:22 UTC, RomanWlm commented on coins/bitcoin/worker/src/main/scala/co/ledger/lama/bitcoin/worker/Worker.scala
> +            error.printStackTrace()
Use Logger here

2020-10-01 09:22 UTC, RomanWlm commented on coins/bitcoin/worker/src/main/scala/co/ledger/lama/bitcoin/worker/Worker.scala
> +          _ <- interpreterService.saveTransactions(account.id, transactions)
How does the interpreter know which addresses has been used to get theses transactions ?

2020-10-01 09:22 UTC, RomanWlm commented on coins/bitcoin/worker/src/main/scala/co/ledger/lama/bitcoin/worker/Worker.scala
> +            syncAccountBatch(account, blockHashCursor, toAddrIndex, toAddrIndex + toAddrIndex)
Is this recursion stack safe ?

2020-10-01 09:22 UTC, RomanWlm commented on coins/bitcoin/worker/src/main/scala/co/ledger/lama/bitcoin/worker/services/ExplorerService.scala
> +        .timeout(conf.timeout)
Good to have explicit and mastered timeout here. We should pan tests to ensure that in case of timeout we are falling down into FAILED sync workflow. Worker emit a failed status.

2020-10-01 09:22 UTC, RomanWlm commented on coins/bitcoin/worker/src/main/scala/co/ledger/lama/bitcoin/worker/services/KeychainService.scala
> +        new Metadata()
Can you clarify here the usage of MetaData ? 
Seems to not be used yet.

2020-10-01 09:27 UTC, nukky94 commented on coins/bitcoin/worker/src/main/scala/co/ledger/lama/bitcoin/worker/Worker.scala
> +            error.printStackTrace()
My bad, no needed actually, I will remove it, the error message is reported into a failed sync event.

2020-10-01 09:28 UTC, nukky94 commented on coins/bitcoin/worker/src/main/scala/co/ledger/lama/bitcoin/worker/Worker.scala
> +          _ <- interpreterService.saveTransactions(account.id, transactions)
We decide to save transactions per batch then, at the end of a sync, call compute operations with all used addresses for an account

2020-10-01 09:28 UTC, nukky94 commented on coins/bitcoin/worker/src/main/scala/co/ledger/lama/bitcoin/worker/services/ExplorerService.scala
> +        .timeout(conf.timeout)
Will do it later yeah 👍

2020-10-01 09:31 UTC, nukky94 commented on coins/bitcoin/worker/src/main/scala/co/ledger/lama/bitcoin/worker/services/KeychainService.scala
> +        new Metadata()
Actually, it's generated when compiling proto for a service:
ex: `KeychainServiceFs2Grpc[IO, Metadata]`, for each methods, we need to pass this empty Metadata()

2020-10-01 09:33 UTC, nukky94 commented on coins/bitcoin/worker/src/it/scala/co/ledger/lama/bitcoin/worker/WorkerIT.scala
> +            val account = AccountIdentifier(keychainId.toString, CoinFamily.Bitcoin, Coin.Btc)
Yeah actually, `key` could be a `keychainId` for bitcoin, or directly the `publicKey` for account based coins. So it's more convenient to type it as `String`

2020-10-01 09:35 UTC, nukky94 commented on .circleci/config.yml
> +  initlama:
I miss knowledges on circleci conf definition.
Could we pair pro later to optimize it later?

2020-10-01 09:43 UTC, nukky94 commented on coins/bitcoin/worker/src/it/resources/application.conf
> +  lookahead-size = 20
Right now, the keychain lookahead size is set with a common env variable:
- For the rest api when creating the keychain
- For the worker when discovering addresses from the keychain

If we want to have a different lookahead size per account, we should:
- create the keychain with this custom size
- register the account with this custom size
- the account manager should pass this custom size at each sync event to the worker

2020-10-01 09:46 UTC, nukky94 commented on coins/bitcoin/worker/src/it/scala/co/ledger/lama/bitcoin/worker/WorkerIT.scala
> +            val keychainService = new KeychainServiceMock
Actually, my idea, for coin specific component IT tests, is to have real resources (pg, rabbitmq, redis, ...) and mocks external services (keychain, interpreter).

We will test all components together on the rest api IT tests

2020-10-01 10:24 UTC, nukky94 commented on coins/bitcoin/worker/src/main/scala/co/ledger/lama/bitcoin/worker/Worker.scala
> +            syncAccountBatch(account, blockHashCursor, toAddrIndex, toAddrIndex + toAddrIndex)
IMO yes since we flatMap each `Pull` (`>>` is an alias for `flatMap(_ => p2)`)

2020-10-01 10:35 UTC, nukky94 commented on coins/bitcoin/worker/src/it/resources/application.conf
> +  lookahead-size = 20
TBD in other ticket (solution 2)

2020-10-01 11:10 UTC, nukky94 commented on coins/bitcoin/worker/src/main/scala/co/ledger/lama/bitcoin/worker/services/KeychainService.scala
> +        new Metadata()
Improvement:
do not instantiate new Metadata() at each grpc calls:
[BACK-926](https://ledgerhq.atlassian.net/browse/BACK-926)

2020-10-01 11:10 UTC, merged