BACK-1589 Fix large account synchronization
LedgerHQ/lama pull request #229
Opened 2021-03-02 15:36 UTC by mbasire-ledger

Limit the usage of memory resources by the Worker

  * Accumulate BatchResult by addresses range in order to detect empty
pages
  * Max block height carry by BatchResult instead of the whole list of
Transactions
  * Bookkeeper hides its internal stream
  * Txs of batch addresses streamed to interpreter (the size of the
batch may be a problem but explorer bug expect us to use a significant
amount of tx by batch)

## What is this about?

Description...

## Cute picture of lama
![lama](https://user-images.githubusercontent.com/11653587/90911060-b5c13280-e3d8-11ea-9e92-d55e347836e2.jpg)

2021-03-03 16:09 UTC, twilgenbus-ledger requested changes
LGTM

Non functionnal changes

2021-03-03 16:09 UTC, twilgenbus-ledger commented on coins/bitcoin/worker/src/main/scala/co/ledger/lama/bitcoin/worker/models/BatchResult.scala
> +          if (blocks.nonEmpty) Some(blocks.max) else None
Could use `maxOption`

2021-03-03 21:10 UTC, mbasire-ledger commented on coins/bitcoin/worker/src/main/scala/co/ledger/lama/bitcoin/worker/models/BatchResult.scala
> +          if (blocks.nonEmpty) Some(blocks.max) else None
done

2021-03-03 21:11 UTC, mbasire-ledger commented on coins/bitcoin/worker/src/main/scala/co/ledger/lama/bitcoin/worker/models/BatchResult.scala
>  case class BatchResult[Tx <: Transaction](
done. BatchResult moved to Bookkeeper.BatchResult

2021-03-03 21:11 UTC, mbasire-ledger commented on coins/bitcoin/worker/src/main/scala/co/ledger/lama/bitcoin/worker/services/Bookkeeper.scala
> +              if (blocks.isEmpty) None else Some(blocks.max)
done

2021-03-03 21:11 UTC, mbasire-ledger commented on coins/bitcoin/worker/src/main/scala/co/ledger/lama/bitcoin/worker/services/Bookkeeper.scala
> +  )(implicit recordable: Recordable[Tx]): IO[String] = recordable.save(interpreter)(accountId, txs)
of course.

2021-03-04 08:34 UTC, twilgenbus-ledger approved these changes

2021-03-04 10:01 UTC, merged