REST API for the Lama project
LedgerHQ/lama pull request #23
Opened 2020-09-30 15:46 UTC by jjayet-ledger

## What is this about?

Description...

## Cute picture of lama
![44337b67caa020912aaf83c6dc5fb2f0](https://user-images.githubusercontent.com/11653587/90911060-b5c13280-e3d8-11ea-9e92-d55e347836e2.jpg)

2020-09-30 16:08 UTC, vbergeron-ledger requested changes

2020-09-30 16:08 UTC, vbergeron-ledger commented on service/src/main/scala/co/ledger/lama/service/App.scala
> +    resources.use {
You should create a ressource Type to hold your application resources.

2020-09-30 16:08 UTC, vbergeron-ledger commented on service/src/main/scala/co/ledger/lama/service/App.scala
> +        val grpcAccountManagedClient  = AccountManagerServiceFs2Grpc.stub[IO](accountManagedChannel)
you could map over the resource in a separate definition
```
val mappedResource = grpcManagedChannel(config).map(MyService.stub[IO])
```

2020-09-30 16:08 UTC, vbergeron-ledger commented on service/src/main/scala/co/ledger/lama/service/App.scala
> +          "/" -> AccountManagerRoutes.routes(keychainManagedChannel, grpcAccountManagedClient)
```suggestion
          "/" -> AccountManagerController.routes(keychainManagedChannel, grpcAccountManagedClient)
```

2020-09-30 16:08 UTC, vbergeron-ledger commented on service/src/main/scala/co/ledger/lama/service/models/AccountManager.scala
> +case class SyncEvent(syncId: String, status: String, payload: String)
Thjis is in the commons no ?

2020-09-30 16:08 UTC, vbergeron-ledger commented on service/src/main/scala/co/ledger/lama/service/routes/AccountManagerRoutes.scala
> +object AccountManagerRoutes {
```suggestion
object AccountManagerController extends Http4sDsl[IO]{
```

2020-09-30 16:08 UTC, vbergeron-ledger commented on service/src/main/scala/co/ledger/lama/service/routes/AccountManagerRoutes.scala
> +    val dsl = new Http4sDsl[IO] {}
You can extend it at the object level

2020-09-30 16:08 UTC, vbergeron-ledger commented on service/src/main/scala/co/ledger/lama/service/routes/AccountManagerRoutes.scala
> +      case _ @GET -> Root / "accountManager" / UUIDVar(accountId) =>
```suggestion
      case GET -> Root / "accountManager" / UUIDVar(accountId) =>
```

2020-09-30 16:08 UTC, vbergeron-ledger commented on service/src/main/scala/co/ledger/lama/service/routes/AccountManagerRoutes.scala
> +          .flatMap(infos => Ok(fromAccountInfoResult(infos)))
```suggestion
          .map(fromAccountInfoResult)
          .flatMap(Ok(_))
```

2020-10-01 11:43 UTC, nukky94 commented on account-manager/src/main/protobuf/service.proto
> +    // XPUB OR Address
it's more about keychain id (for bitcoin), public key (for account based coins)

2020-10-01 12:02 UTC, nukky94 requested changes

2020-10-01 12:02 UTC, nukky94 commented on service/src/main/scala/co/ledger/lama/service/utils/ProtobufUtils.scala
> +import co.ledger.lama.manager.protobuf.account_manager.{
This is exactly why we need to use this option:
```
scalapbCodeGeneratorOptions += CodeGeneratorOption.FlatPackage
```

From doc:
```
CodeGeneratorOption.FlatPackage - If true, the compiler does not append the proto base file name
```

2020-10-01 12:02 UTC, nukky94 commented on build.sbt
>      sharedSettings
After rebasing, you can explicitly use protos from specific directories:
```
scalapbCodeGeneratorOptions += CodeGeneratorOption.FlatPackage,
PB.protoSources in Compile += Seq(file("coins/bitcoin/keychain/pb/keychain"), file("account-manager/src/main/protobuf"))
```

2020-10-01 17:57 UTC, nukky94 commented on build.sbt
> +    PB.protoSources in Compile += file("coins/bitcoin/common/src/main/protobuf"),
Why do you move the account manager proto into this directory?
The `account-manager.proto` should be into `account-manager/src/main/protobuf`

2020-10-01 19:53 UTC, jjayet-ledger commented on service/src/main/resources/application.conf
> +apis = {
I know but I just find it cleaner

2020-10-02 08:29 UTC, nukky94 commented on account-manager/src/main/scala/co/ledger/lama/manager/Service.scala
> +              Payload(AccountIdentifier(account.key, account.coinFamily, account.coin))
But why ?
Actually, we really want to keep the current behaviour of `AccountIdentifier` since we need to pass the `key`, `coinFamily` and `coin` to the payload of event sent to the worker.

2020-10-02 10:36 UTC, onyb commented on account-manager/src/main/scala/co/ledger/lama/manager/Service.scala
> +              Payload(AccountIdentifier(account.key, account.coinFamily, account.coin))
I see your point. Maybe it's better than the worker getting the key from the account UUID. 👍

2020-10-02 11:03 UTC, nukky94 commented on service/src/main/resources/application.conf
> +apis = {
maybe it's clearer like that:

```
server { ... }

account-manager { ... }

bitcoin {
  keychain { ... }

  interpreter { ... }
}
```

2020-10-02 11:14 UTC, nukky94 commented on account-manager/src/main/scala/co/ledger/lama/manager/Service.scala
> +              Payload(AccountIdentifier(account.key, account.coinFamily, account.coin))
I don't know if it's possible to get back the infos on an obfuscated UUID since we construct the uuid like that:
`UUID.nameUUIDFromBytes((key + coinFamily.name + coin.name).getBytes)`

2020-10-02 11:14 UTC, nukky94 requested changes
last remark: https://github.com/LedgerHQ/lama/pull/23#discussion_r498755855

2020-10-02 12:32 UTC, nukky94 approved these changes

2020-10-02 12:37 UTC, merged