Back-919 Save Operations
LedgerHQ/lama pull request #24
Opened 2020-10-01 15:38 UTC by estrauser-ledger

## What is this about?
- Compute and save operations algo
- Use new data model
- Probably some other stuff

## Cute picture of lama
![Lamasticot](https://user-images.githubusercontent.com/1628443/94831295-d7b4c880-040c-11eb-98e8-304cbcb5954c.png)

2020-10-01 15:40 UTC, estrauser-ledger commented
There are probably some ugly stuff still, I couldn't get away from "asInstanceOf" 'cause I'm tired ~~

2020-10-02 09:51 UTC, estrauser-ledger commented
ABORT !!
Sorry I made a mistake, I thought the 'id' field in Transaction was the accountId, not the transaction Id.
I have to go through the whole PR and fix this

2020-10-02 09:55 UTC, nukky94 requested changes

2020-10-02 09:55 UTC, nukky94 commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/App.scala
> -        new FakeInterpreter().definition
since we don't need it anymore for the app, could you move `FakeInterpreter`  into `src/test` ?

2020-10-02 09:55 UTC, nukky94 commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Interpreter.scala
> +      _ =
why are you fire and forget the computation?

2020-10-02 09:55 UTC, nukky94 commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Interpreter.scala
> +    IO.pure(Empty())
You can call `OperationComputer.compute` and store results into a mutable list.
It will be great to test it on the `InterpreterSpec` since we need to list transactions (and asserts on operations)

2020-10-02 09:55 UTC, nukky94 commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Interpreter.scala
> +      accountId <- IO.fromTry(Try(UuidUtils.bytesToUuid(request.accountId).get))
There's an `IO.fromOption`

2020-10-02 09:55 UTC, nukky94 commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Interpreter.scala
> +          .map { operation =>
`traverse` to have an `IO[List[Int]]`

2020-10-02 09:55 UTC, nukky94 commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/OperationComputer.scala
> +          .contains(output.address)
You go through the list multiple times with `.filter` and `.map`.
You can optimize by using `collectFirst().isDefined`

```
       addresses
          .collectFirst {
            case a if a.changeType == INTERNAL && a.accountAddress == output.address => a
          }
          .isDefined
```

2020-10-02 09:55 UTC, nukky94 commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/OperationComputer.scala
> +          .contains(output.address)
same

2020-10-02 09:55 UTC, nukky94 commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/OperationComputer.scala
> +      .sum
```
   tx.inputs
      .collect {
        case input: DefaultInput if addresses.exists(_.accountAddress == input.address) =>
          input.value
      }.sum
```

2020-10-02 10:02 UTC, nukky94 commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/OperationComputer.scala
> +      .sum
You go through the list multiple times with `.filter` and `.map` and `.contains`.
`collect` seems more appropriate:
```
    tx.outputs
      .collect {
        case o if addresses.exists(a => a.changeType == INTERNAL && a.accountAddress == o.address) =>
          o.value
      }.sum
```

2020-10-02 10:02 UTC, nukky94 commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/OperationComputer.scala
> +      .sum
same

2020-10-02 13:54 UTC, estrauser-ledger commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Interpreter.scala
> +      _ =
What should I do with it ? The service is just a trigger, it needs an Empty response.

2020-10-02 14:02 UTC, jjayet-ledger commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/OperationComputer.scala
> +      .sum
I agree with @estrauser-ledger, at first glance, his approach seems easier to read while being the same speed because of compiler optimisations.
Maybe a more experienced Scala dev would prefer the `collect` way.

Either solutions are fine by me.

2020-10-02 14:03 UTC, estrauser-ledger commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Interpreter.scala
> +      accountId <- IO.fromTry(Try(UuidUtils.bytesToUuid(request.accountId).get))
`fromOption` needs a `orElse` function and in the current architecture I don't know what to make of these cases except make them explode and go back to the worker. the `Try` does this for me.

2020-10-02 15:30 UTC, jjayet-ledger approved these changes

2020-10-02 16:50 UTC, nukky94 commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Interpreter.scala
> +      _ =
Actually, if you fire and forget the computation, the worker never know if there's an error (that's why we need this computation should be as part of the effect of the returned IO

2020-10-02 16:52 UTC, nukky94 commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Interpreter.scala
> +      accountId <- IO.fromTry(Try(UuidUtils.bytesToUuid(request.accountId).get))
```
def fromOption[A](option: Option[A])(orElse: => Throwable): IO[A]
Lifts an Option[A] into the IO[A] context, raising the throwable if the option is empty.
```

2020-10-05 16:23 UTC, nukky94 requested changes
Some remarks to do now.

2020-10-05 16:23 UTC, nukky94 commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Queries.scala
> +              AND account_id = ${accountId.toString}
to refactor on another ticket (BACK-948) since we would like to store account_id as UUID instead of varchar

2020-10-05 16:23 UTC, nukky94 commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Queries.scala
> +          Block(hash = hash, height = height, time = time)
`Block(hash, height, time)`

2020-10-05 16:23 UTC, nukky94 commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Queries.scala
> +          Output(outputIndex = outputIndex, value = value, address = address, scriptHex = scriptHex)
Same, reduce boilerplate

2020-10-05 16:23 UTC, nukky94 commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Queries.scala
> +            NULL,
⚠️

2020-10-05 16:23 UTC, nukky94 commented on coins/bitcoin/common/src/main/protobuf/interpreter.proto
> +}
Actually we want a Operation with also infos from its corresponding tx. (let's do it later in another ticket: BACK-949)

2020-10-05 20:24 UTC, vbergeron-ledger commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Interpreter.scala
> +              .void
- The anonymous function in the `traverse` is too long, you should extract it
- You should update the UUIDUtils to create a InvalidUUID Exception
- You could batch the two calls to the DB in a tuple then transact it.

2020-10-05 20:24 UTC, vbergeron-ledger commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Interpreter.scala
> +              .void
```suggestion
        _ <- (Queries.upsertBlock(tx.block), Queries.saveTransaction(tx, accountId)).tupled.transact(db).void
        } yield ()
```

2020-10-06 10:09 UTC, estrauser-ledger commented on coins/bitcoin/common/src/main/protobuf/interpreter.proto
> +}
Will be the subject of https://ledgerhq.atlassian.net/browse/BACK-949

2020-10-06 10:13 UTC, estrauser-ledger commented on coins/bitcoin/common/src/main/scala/co/ledger/lama/bitcoin/common/models/package.scala
> +      time: String,
Will be the subject of https://ledgerhq.atlassian.net/browse/BACK-932

2020-10-06 10:16 UTC, estrauser-ledger commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Queries.scala
> +            NULL,
will be the subject of https://ledgerhq.atlassian.net/browse/BACK-954

2020-10-06 10:16 UTC, estrauser-ledger commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Queries.scala
> +          Output(outputIndex = outputIndex, value = value, address = address, scriptHex = scriptHex)
will be the subject of https://ledgerhq.atlassian.net/browse/BACK-954

2020-10-06 10:16 UTC, estrauser-ledger commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Queries.scala
> +          Block(hash = hash, height = height, time = time)
will be the subject of https://ledgerhq.atlassian.net/browse/BACK-954

2020-10-06 10:16 UTC, estrauser-ledger commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Queries.scala
> +              AND account_id = ${accountId.toString}
Will be the subject of https://ledgerhq.atlassian.net/browse/BACK-948

2020-10-06 10:18 UTC, estrauser-ledger commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Interpreter.scala
> +      }
Will be the subject of https://ledgerhq.atlassian.net/browse/BACK-955

2020-10-06 10:18 UTC, estrauser-ledger commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Interpreter.scala
> +    //TODO deal with ordering
Will be the subject of https://ledgerhq.atlassian.net/browse/BACK-956

2020-10-06 12:20 UTC, nukky94 approved these changes

2020-10-06 12:22 UTC, merged