Back 965 belongs
LedgerHQ/lama pull request #33
Opened 2020-10-08 14:10 UTC by estrauser-ledger

## What is this about?

Big refacto : now operations and transactions are separate.
Also flag inputs and outputs belonging to account.

## Cute picture of lama
![doublellama](https://user-images.githubusercontent.com/1628443/95470180-c6c20500-0980-11eb-9aa8-5c6c2c3aa703.jpg)

2020-10-08 16:05 UTC, jjayet-ledger requested changes

2020-10-08 16:05 UTC, jjayet-ledger commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Interpreter.scala
> +  val tranctionInterpreter = new TransactionInterpreter(db)
`
val transactionInterpreter = new TransactionInterpreter(db)
`

2020-10-08 16:05 UTC, jjayet-ledger commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/OperationInterpreter.scala
> +    } yield (inputs :: outputs).sum).transact(db)
I do find this style a little ugly.
I'd prefer a variable but it's more of an aesthetic choice :)

2020-10-08 16:08 UTC, estrauser-ledger commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/Interpreter.scala
> +  val tranctionInterpreter = new TransactionInterpreter(db)
lol :+1:

2020-10-09 08:32 UTC, jjayet-ledger requested changes

2020-10-09 08:32 UTC, jjayet-ledger commented on coins/bitcoin/interpreter/src/main/resources/db/migration/V1__bitcoin_schema.sql
>      height INTEGER NOT NULL,
This is declared as BitInt (long) elsewhere.
Either we change this type to BitInt or every other types to Int

2020-10-09 12:53 UTC, estrauser-ledger commented on coins/bitcoin/common/src/main/scala/co/ledger/lama/bitcoin/common/models/Explorer.scala
> +      height: Long,
BigInt

2020-10-09 13:15 UTC, estrauser-ledger commented on coins/bitcoin/interpreter/src/main/scala/co/ledger/lama/bitcoin/interpreter/TransactionQueries.scala
> +
no need

2020-10-09 13:20 UTC, nukky94 approved these changes

2020-10-09 13:20 UTC, jjayet-ledger approved these changes

2020-10-09 13:20 UTC, merged