BACK-957: Now able to update SyncFrequency for an account
LedgerHQ/lama pull request #47
Opened 2020-10-15 09:33 UTC by jjayet-ledger

## What is this about?

- Adds a new PUT endpoint which allows for SyncFrequency update
- Tests that

## Cute picture of lama
![lama](https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSIrtTKj99hGmA1yxJ1ZcHrmXg1W2ph-EZjSA&usqp=CAU)

2020-10-15 10:10 UTC, nukky94 requested changes

2020-10-15 10:10 UTC, nukky94 commented on service/src/main/scala/co/ledger/lama/service/routes/AccountController.scala
> +      case req @ PUT -> Root =>
It's more idiomatic to have `PUT /accounts/:id` and just have `sync_frequency` in the payload

2020-10-15 10:10 UTC, nukky94 commented on service/src/main/scala/co/ledger/lama/service/routes/AccountController.scala
> +          )
Actually it's very dangerous to call account manager registerAccount service to update info (it will erase your last cursor, coinFamily and coin fields).
It's better to refactor registerAccount to deal only with creation, and have an `updateAccount` just for the update

2020-10-15 17:38 UTC, nukky94 requested changes

2020-10-15 17:38 UTC, nukky94 commented on account-manager/src/main/protobuf/account-manager.proto
> +    bytes accountId = 1;
`account_id`

2020-10-15 17:38 UTC, nukky94 commented on account-manager/src/main/scala/co/ledger/lama/manager/Queries.scala
> +            DO UPDATE SET account_id = $accountId
you can remove `ON CONFLICT ... DO ...` part since we want it to failed actually

2020-10-16 08:59 UTC, jjayet-ledger commented on account-manager/src/main/scala/co/ledger/lama/manager/Queries.scala
> +            DO UPDATE SET account_id = $accountId
Done!

2020-10-16 12:53 UTC, nukky94 approved these changes

2020-10-16 12:54 UTC, merged